// Regenerate the per-directory barrels: components/ui/index.ts and
// components/ai-elements/index.ts (sorted `export *` of every component).
// Run after adding/removing/syncing components so the barrels stay in sync.
// Usage: node scripts/gen-barrels.mjs
import { readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = dirname(dirname(fileURLToPath(import.meta.url)));
const HEADER = "// AUTO-GENERATED by scripts/gen-barrels.mjs — do not edit by hand.\n";

function genBarrel(dir) {
  const abs = join(PKG, dir);
  const names = readdirSync(abs)
    .filter((f) => /\.tsx?$/.test(f) && f !== "index.ts" && f !== "index.tsx")
    .map((f) => f.replace(/\.tsx?$/, ""))
    .sort();
  const body = names.map((n) => `export * from "./${n}";`).join("\n");
  writeFileSync(join(abs, "index.ts"), HEADER + "\n" + body + "\n");
  console.log(`${dir}/index.ts — ${names.length} exports`);
}

genBarrel("components/ui");
genBarrel("components/ai-elements");
